wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711997380.0
    t:
      1:
      - 55
      3:
      - 16
      - 23
      4: 3.8.19
      5: 0.16.5
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
